# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build, Test and Publish .NET 9 Web App

on:
  push:
    branches: [ "master", "QA", "Dev" ]
  pull_request:
    branches: [ "master", "QA", "Dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
 
    env:
      BUILD_CONFIGURATION: Release
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Install .NET 9 SDK (preview)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.301'
          include-prerelease: true
 
      - name: Restore dependencies
        run: dotnet restore
 
      - name: Build project
        run: dotnet build --configuration $BUILD_CONFIGURATION
 
      - name: Run unit tests
        run: dotnet test --configuration $BUILD_CONFIGURATION --no-build --logger trx
 
      - name: Publish Web App
        run: dotnet publish **/GestionMedica.Web/GestionMedica.Web.csproj --configuration $BUILD_CONFIGURATION --output ./publish
 
      - name: Upload artifact (zip)
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ./publish
